- name: blacklist i2c_piix4
  hosts: all
  gather_facts: false
  become: true
  remote_user: ansible
  become_method: sudo
  tasks:
    - name: blacklist i2c_piix4
      lineinfile:
        path: /etc/modprobe.d/no_i2c_piix4.conf
        create: yes
        line: blacklist i2c_piix4