---
- name: Allow incomming traffic on local firewall 
  hosts: all
  become: true
  tasks:
    - name: Read variables from file
      include_vars: vars/zmienne.yml

    - name: Ensure firewalld service is running and enabled
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow incomming traffic on local firewall - ports provided by clustomer
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
      loop: "{{ firewalld_open_ports[inventory_hostname] }}"

    - name: Always reload firewalld after adjustment
      service:
        name: firewalld
        state: reloaded
