---
- name: Configure Firewalld on PLM servers
  hosts: all
  become: true
  vars_files:
    - vars/firewalld_ports_definitions.yml

  tasks:
    - name: Define firewalld service for each server
      firewalld:
        name: 3ds
        permanent: yes
        ports: "{{ item.ports }}"
        immediate: yes
        state: enabled
      loop: "{{ servers }}"

    - name: Enable incoming traffic for the 3ds services
      firewalld:
        service: 3ds
        state: enabled

    - name: Ensure firewalld service is running and enabled
      systemd:
        name: firewalld
        state: started
        enabled: yes
