---
- name: SSHD crypto-policies configuration to eliminate vulnerability CVE-2023-48795 (Terrapin) by enforcing disuse ChaCha20-Poly1305, CTR-EtM, CBC-EtM
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  ignore_errors: yes


  tasks:
#### RHEL7
    - name: crypto-policies for RHEL7
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
          MACs hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160
          KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
      notify: Reload SSH

### RHEL8
    - name: crypto-policies for RHEL8 1/2
      blockinfile:
        path: /etc/sysconfig/sshd
        block: |
          CRYPTO_POLICY=
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '9'
      notify: Reload SSH

    - name: crypto-policies for RHEL8 2/2
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
          MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512
          KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '9'
      notify: Reload SSH

#### RHEL9
    - name: crypto-policies for RHEL9
      blockinfile:
        path: /etc/ssh/sshd_config.d/49-crypto-policies.conf
        block: |
          Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
          MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512
          KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        create: yes
      when: ansible_facts['distribution'] == 'RedHat' and ansible_facts['distribution_major_version'] == '10'
      notify: Reload SSH

  handlers:
    - name: Reload SSH
      systemd:
        name: sshd
        state: reloaded
