- name: disable transparent_hugepage
  hosts: all
  gather_facts: false
  become: true
  remote_user: ansible
  become_method: sudo
  tasks:
    - name: disable transparent_hugepage in /etc/default/grub
      lineinfile:
        state: present
        dest: /etc/default/grub
        backrefs: yes
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.* transparent_hugepage)\"[^\"]+)(\".*)'
        line: '\1 transparent_hugepage=never\2'

    - name: check if rebuild grub is needed, maybe entry was already done previously, so no rebuild is needed
      command: "find /etc/default/grub -cmin -10"
      register: grub_out

    - name: write grub configuration file
      command: "{{ item }}"
      with_items:
        - grub2-mkconfig -o /boot/grub2/grub.cfg
        - dracut -v -f
      when: grub_out.stdout | regex_search('grub')