- name: Install additional packages 
  hosts: all
  gather_facts: true
  become: true
  remote_user: ansible
  become_method: sudo
  tasks:
    - name: Enable codeready-builder repository RHEL8
      rhsm_repository:
        name: "codeready-builder-for-rhel-8-x86_64-rpms"
        state: enabled
      when: ansible_distribution_major_version == '8'

    - name: Enable codeready-builder repository RHEL9
      rhsm_repository:
        name: "codeready-builder-for-rhel-9-x86_64-rpms"
        state: enabled
      when: ansible_distribution_major_version == '9'

    - name: RPM PGP Key Import RHEL8
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      when: ansible_distribution_major_version == '8'  

    - name: RPM PGP Key Import RHEL9
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
      when: ansible_distribution_major_version == '9'

    - name: Enable epel-repository RHEL8
      dnf:
        name:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      when: ansible_distribution_major_version == '8'    

    - name: Enable epel-repository RHEL9
      dnf:
        name:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      when: ansible_distribution_major_version == '9'    
          
    - name: Install additional packages 
      dnf:
        name:
          - wget
          - bc
          - sysstat
          - tcpdump
          - unzip
          - nc
          - mc
          - openssh-clients
          - vim
          - subscription-manager
          - rsync
          - telnet
          - dnf-utils
          - lsof
          - bzip2
          - bind-utils
          - dstat
          - net-tools
          - nmap
          - pwgen
          - mtr
          - htop
          - numactl
          - pcp
          - bash-completion
          - ncdu
          - dos2unix
          - git
          - nfs-utils
          - samba-client
          - cifs-utils
          - iscsi-initiator-utils
          - screen
          - tmux
          - iotop
          - atop
          - dnf-automatic
          - perl
          - python3-pip
          - sg3_utils
          - nload
          - glances
          - xterm
          - nethogs
          - rpmconf