- name: Install updates for all packages
  hosts: all
  gather_facts: false
  become: true
  remote_user: ansible
  become_method: sudo
  tasks:
    - name: Install updates for all packages
      dnf:
        name: "*"
        state: latest