- name: Install updates for all installed packages
  hosts: "{{ ansible_host }}"
  gather_facts: false
  become: true
  remote_user: ansible
  become_method: sudo
  tasks:
    - name: Install updates for all installed packages
      dnf:
        name: "*"
        state: latest