- name: Install updates for all packages
  hosts: all
  gather_facts: false
  become: true
  remote_user: ansible
  become_method: sudo
  tasks:
    - name: Package installation
      dnf:
        name:
          - netdata
        state: latest

    - firewalld:
        port: 19999/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Changing bind address from localhost to any
      replace:
        path: /etc/netdata/netdata.conf
        regexp: 'bind to = localhost'
        replace: 'bind to = any'

    - name: Change group from netdata to root
      replace:
        path: /etc/netdata/netdata.conf
        regexp: 'web files group = netdata'
        replace: 'web files group = root'

    - name: Start and enable netdata
      service:
        name: netdata
        state: started
        enabled: yes