- name: enable cockpit
  hosts: all
  gather_facts: false
  become: true
  remote_user: ansible
  become_method: sudo
  tasks:
    - name: package installation
      dnf:
        name:
          - cockpit
        state: latest

    - name: Firewald status check
      command: systemctl is-active firewalld
      register: firewalld_status
      changed_when: false
      failed_when: false

    - name: Reconfigure firewalld if enabled
      firewalld:
        service: cockpit
        permanent: yes
        state: enabled
        immediate: yes
      when: firewalld_status.stdout == "active"

    - name: start and enable cockpit
      service:
        name: cockpit.socket
        state: started
        enabled: yes